name: tests

on:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout source
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2
          coverage: xdebug
          extensions: bcmath, curl, dom, fileinfo, gd, intl, mbstring, pdo, pdo_mysql, pdo_pgsql, pdo_sqlite, sqlite, xml, zip

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: npm

      - name: Install Node dependencies
        run: npm ci

      - name: Install Composer dependencies
        run: composer install --no-ansi --no-interaction --no-progress --prefer-dist --optimize-autoloader

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Build assets
        run: npm run build

      - name: Tests
        run: ./vendor/bin/phpunit
